src/server/base_restate_server.ts
Mutating is fine, but ensure its scoped to the base server - someone might have multiple servers created somewhere inside their application with the same names - this currently would cause a conflict
=> Avoid global dyn rpc descriptor

src/connection/lambda_connection.ts, src/server/restate_lambda_handler.ts
=> Support already completed journals in lambda handlers

src/restate_context.ts, src/restate_context_impl.ts, src/server/restate_lambda_handler.ts, src/utils/rand.ts, test/protoutils.ts, test/utils.test.ts
By using the full 256 bits from the sha256 hash, we get extremely good state collision resistance; it is now pretty much impossible for two different invocation ids to produce the same state. As a result, we can be a lot more confident in the quality of our pseudorandom numbers.
=> Move to xorshiro for rand generation

src/restate_context_impl.ts, src/types/errors.ts, test/protoutils.ts
These are useful for influencing http responses. Our users may not import grpc, and shouldn't need to know about grpc.
=> Ship all grpc error codes

src/server/base_restate_server.ts, src/utils/utils.ts, test/utils.test.ts
We pass directly to the google.protobuf.Value conversion function, which is fine, except that this is not as clever as JSON.stringify, and will treat objects like Date as empty objects. To match stringify, we should respect the toJSON() function which may be present on the value to be converted.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description
Fixes #198
=> Convert rpc handler responses into a JSON-safe 'any' type

proto/protocol.proto, src/invocation.ts, src/journal.ts, src/state_machine.ts, src/types/errors.ts, test/get_state.test.ts, test/protoutils.ts, test/sleep.test.ts, test/state_machine.test.ts
This commit updates the SDK to the latest service protocol version. Part of it is to enable failure variants for the GetState, PollInputStream and SleepEntryMessages so that the runtime can cancel these entries. This commit also adds tests for verifying the changes.
This fixes #210.
=> Add failure variant for GetState, PollInputStream and SleepEntryMessage

proto/protocol.proto, src/state_machine.ts, src/types/protocol.ts, test/awakeable.test.ts, test/complete_awakeable.test.ts, test/eager_state.test.ts, test/get_and_set_state.test.ts, test/get_state.test.ts, test/lambda.test.ts, test/protoutils.ts, test/send_request.test.ts, test/side_effect.test.ts, test/sleep.test.ts, test/state_machine.test.ts
Part of https://github.com/restatedev/service-protocol/issues/49
=> Introduce EndMessage

src/restate_context_impl.ts, src/types/errors.ts, src/utils/utils.ts
=> Remove cause from TerminalError, as it's not supported by the protocol

src/server/base_restate_server.ts, src/server/restate_lambda_handler.ts, src/server/restate_server.ts
Minor logging changes
A few small logging changes to align better with how the server interacts with the SDK in some cases. The most notable is that when we discover services we don't always "register" them (in dry-run mode) so that SDK should just log that it's announcing those services instead. Additionally. Using the word "registering" in logs might confuse users as it's not registering those services to restate server but rather just binding those services on the open port.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/sdk-typescript/pull/225).
* #226
* __->__ #225
=> Minor logging changes

src/state_machine.ts
Allow printing stacktrace when invocations finish with an error
=> Allow printing stacktrace when invocations finish with an error

src/restate_context_impl.ts, src/server/base_restate_server.ts, test/side_effect.test.ts
=> Add guard for RestateContext.sideEffect await

src/restate_context_impl.ts, src/server/base_restate_server.ts, src/types/protocol.ts, src/utils/assumptions.ts, test/protoutils.ts
Awakeable identifiers following the new ID scheme
Bonus: `s/assumpsions/assumptions/`
Server side in https://github.com/restatedev/restate/pull/1120 
Test Plan:
Using sample code to generate an awakeable and resolved it with
```
curl localhost:8080/dev.restate.Awakeables/Resolve -H 'content-type: application/json' -d '{"id": "prom_1NMyOAvDK2CcBjUH4Rmb7eGBp0DNNDnmsAAAAAQ", "json_result": ""}'
```
```
[restate] [2024-01-25T18:54:01.682Z] DEBUG: [CheckoutProcess/checkout] [inv_13q6r7rhzaG85fs0bfyqW8cubIUYJFjvBT] : Resuming (replaying) function.
Awakeable is:  prom_1NMyOAvDK2CcBjUH4Rmb7eGBp0DNNDnmsAAAAAQ
Awakeable COMPLETED  prom_1NMyOAvDK2CcBjUH4Rmb7eGBp0DNNDnmsAAAAAQ
```
=> Awakeable identifiers following the new ID scheme

src/restate_context_impl.ts
Currently, the RPC handler API does not respect the `RetrySettings`, because it forgets to pass that optional parameter down to the underlying context.
=> Properly pass RetrySettings parameter in the functional rpc API.

.github/workflows/test.yml
Buf is anyways available as a dev dependency and works without any setup action.
(The release workflow doesn't have that action).
=> Remove redundant buf setup action in testing workflow.

src/server/base_restate_server.ts
Rejects empty strings and strings containing a slash '/'.
=> Some sanity checking for service names.

src/io/decoder.ts, test/message_coders.test.ts
=> Check protocol version

proto/protocol.proto, src/journal.ts, src/local_state_store.ts, src/restate_context.ts, src/restate_context_impl.ts, src/types/protocol.ts, src/types/types.ts, test/protoutils.ts, test/state_keys.test.ts
=> Add `ctx.stateKeys()`

src/io/decoder.ts, test/protocol_stream.test.ts, test/protoutils.ts
Part of https://github.com/restatedev/restate/issues/1159
=> Bump protocol version

src/endpoint.ts, src/endpoint/endpoint_impl.ts, src/endpoint/lambda_handler.ts, test/lambda.test.ts
Fix issue found in verification test, where i was picking up the request id from the wrong place.
=> Fix lambda context propagation

packages/restate-sdk/proto/javascript.proto, packages/restate-sdk/proto/protocol.proto, packages/restate-sdk/src/context_impl.ts, packages/restate-sdk/src/journal.ts, packages/restate-sdk/src/types/errors.ts, packages/restate-sdk/src/types/protocol.ts, packages/restate-sdk/test/protoutils.ts, packages/restate-sdk/test/side_effect.test.ts
This PR use the `SideEffectMessageEntry` from the protocol And populate the name field of the run() field.
By reusing a SideEffectMessageEntry, common tools like the cli and the ui can introspect and display the side effect message across the sdks.
Note: e2e should not pass, before the runtime changes has landed.
=> [protocol] Use the SideEffectMessage from the protocol

packages/restate-sdk/src/context_impl.ts, packages/restate-sdk/test/promise_combinators.test.ts, packages/restate-sdk/test/testdriver.ts
This is a hotfix, a more meaningful fix would be to implement 'transform' for combineable promises so that they stay combineable
=> Avoid transform after invoke, which appears to break CombineablePromise

packages/restate-sdk/proto/discovery.proto, packages/restate-sdk/proto/protocol.proto, packages/restate-sdk/src/context_impl.ts, packages/restate-sdk/src/endpoint/http2_handler.ts, packages/restate-sdk/src/endpoint/lambda_handler.ts, packages/restate-sdk/src/io/decoder.ts, packages/restate-sdk/src/io/encoder.ts, packages/restate-sdk/src/state_machine.ts, packages/restate-sdk/src/types/protocol.ts, packages/restate-sdk/src/types/types.ts, packages/restate-sdk/test/lambda.test.ts, packages/restate-sdk/test/message_coders.test.ts, packages/restate-sdk/test/protocol_stream.test.ts, packages/restate-sdk/test/protoutils.ts, packages/restate-sdk/test/testdriver.ts
This commits add support for verifying the service discovery protocol and
the service protocol which are now communicated via HTTP headers.
This fixes https://github.com/restatedev/sdk-typescript/issues/356.
=> Add service discovery and service protocol checks 

package-lock.json, package.json, packages/restate-sdk-clients/package.json, packages/restate-sdk-clients/tsconfig.json, packages/restate-sdk-core/package.json, packages/restate-sdk-core/tsconfig.json, packages/restate-sdk-examples/package.json, packages/restate-sdk/package.json, packages/restate-sdk/scripts/version.mjs, packages/restate-sdk/tsconfig.json, tsconfig.base.json
This PR changes the `dist` directory to have two subdirs `esm` and `cjs` with different entrypoints in package.json
The files in the cjs directory are identical to the files previously produced in dist
The files in the esm directory are valid esm modules which will be used in esm import contexts
=> Convert to ESM modules

packages/restate-sdk/src/endpoint/cloudflare_endpoint.ts, packages/restate-sdk/src/endpoint/handlers/cloudflare.ts
Must be an object, not a class, and can't leak CF types across export boundary
=> Fix cloudflare worker exported types

packages/restate-sdk-clients/package.json, packages/restate-sdk-core/package.json, packages/restate-sdk/package.json
We don't need to support node v10, but we do need to support modern node with tsc using node10 module resolution, sadly.
https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main/examples/node_modules/types-versions-wildcards
=> Use typesVersions workaround to support node10 resolution

.github/workflows/test.yml
Previously it would insert it even in packages that don't include that package
=> Update, don't upsert, snapshot version

packages/restate-sdk/src/journal.ts
Previously they would hang forever if replayed after a suspension
=> Ensure that we resolve completepromise messages on replay

packages/restate-sdk/src/common_api.ts, packages/restate-sdk/src/connection/connection.ts, packages/restate-sdk/src/endpoint.ts, packages/restate-sdk/src/endpoint/endpoint_builder.ts, packages/restate-sdk/src/endpoint/fetch_endpoint.ts, packages/restate-sdk/src/endpoint/handlers/generic.ts, packages/restate-sdk/src/endpoint/handlers/lambda.ts, packages/restate-sdk/src/endpoint/lambda_endpoint.ts, packages/restate-sdk/src/endpoint/node_endpoint.ts, packages/restate-sdk/src/logger.ts, packages/restate-sdk/src/state_machine.ts, packages/restate-sdk/src/utils/message_logger.ts, packages/restate-sdk/test/awakeable.test.ts, packages/restate-sdk/test/protocol_stream.test.ts, packages/restate-sdk/test/protoutils.ts, packages/restate-sdk/test/testdriver.ts, packages/restate-sdk/tsconfig.json
Fixes #339
Allows you to provide a logging function that receives some parameters about the log (the context of the invocation, the level, where it came from) in addition to the message and extra params and allows the user to decide what to do with it
=> Allow providing a custom logger

packages/restate-sdk/src/context.ts, packages/restate-sdk/src/context_impl.ts, packages/restate-sdk/src/endpoint/handlers/fetch.ts, packages/restate-sdk/src/endpoint/handlers/generic.ts, packages/restate-sdk/src/endpoint/handlers/lambda.ts, packages/restate-sdk/src/endpoint/node_endpoint.ts, packages/restate-sdk/src/state_machine.ts, packages/restate-sdk/test/testdriver.ts
https://discord.com/channels/1128210118216007792/1136316066696532069/1268606950833127454
=> Make it possible to get extra args provided to functional handlers

packages/restate-sdk/src/state_machine.ts
isReplaying isn't always accurate as it transitions at the next journal entry. What we care about is whether the next entry will replay (if not, we should log)
=> Fix replaying detection in logger.ts

packages/restate-sdk/src/endpoint/handlers/generic.ts
This will vary from platform to platform; in node the url is always relative, but in cloudflare et all it may be absolute. The identity verification will fail if we don't have it as relative.
=> Support absolute and relative urls in request object

packages/restate-sdk/src/endpoint/endpoint_builder.ts
The SDK is communicating a wrong protocol version. It claims to support 2, while it doesn't, leading to an invocation failure: https://github.com/restatedev/restate/actions/runs/10559650982/job/29252180888?pr=1893
=> The supported maxProtocolVersion should be 1, instead of 2.

package-lock.json, packages/restate-sdk/src/endpoint/handlers/generic.ts, packages/restate-sdk/src/endpoint/request_signing/v1.ts, packages/restate-sdk/src/endpoint/request_signing/validate.ts, packages/restate-sdk/src/types/components.ts, packages/restate-sdk/test/testdriver.ts
THe runtime does not absolutise its paths against the http url - it just signs something like /invoke/a/b or /discover. We should normalise the paths we receive when checking against the signature.
=> Normalise incoming paths before checking them against signature

packages/restate-sdk/src/context_impl.ts, packages/restate-sdk/src/endpoint/handlers/generic.ts, packages/restate-sdk/src/logging/logger_transport.ts
So you can get access to headers, extra args
=> Include request struct in logger context

README.md
The README mentions `npm run example` which doesn't exist.
This PR replaces it with working commands from the examples package.
Based on a discussion in discord, this just runs the deployments/services without registering or executing them.
=> Replace commands to run examples with working ones

packages/restate-e2e-services/src/app.ts, packages/restate-sdk-clients/src/api.ts, packages/restate-sdk-clients/src/ingress.ts, packages/restate-sdk/src/common_api.ts, packages/restate-sdk/src/endpoint.ts, packages/restate-sdk/src/endpoint/fetch_endpoint.ts, packages/restate-sdk/src/endpoint/lambda_endpoint.ts, packages/restate-sdk/src/endpoint/node_endpoint.ts, packages/restate-sdk/src/logging/logger_transport.ts, packages/restate-sdk/src/types/rpc.ts
Remove
* ServiceBundle API
* old custom logger API, they have been renamed to `LogMetadata` and `LoggerTransport`
* old lambda handler API, use the `restate-sdk-lambda` package for that
* old input/output serializer/deserializers functions and the raw attribute. Use custom `serde`s for those.
=> Remove deprecated APIs

packages/restate-sdk/src/endpoint/handlers/generic.ts
This prevents the runtime from detecting a protocol version violation, thus not showing the nice error message.
=> Fix propagation of error when creating the VM. 

package-lock.json, package.json, packages/restate-sdk-examples/package.json, packages/restate-sdk-testcontainers/package.json
Trying to address issues in https://github.com/restatedev/sdk-typescript/pull/508
The current ⁠`@release-it-plugins/workspaces` version doesn't support ⁠`release-it` 18, which fixes a security vulnerability. There's an open PR (https://github.com/release-it-plugins/workspaces/pull/118) that merely updates the peerDependency versions. Since ⁠`@release-it-plugins/workspaces` should work with release-it 18, I'm temporarily overriding the dependency version.
=> Bump outdated dependencies

packages/restate-sdk/src/context.ts
=> Improve `CombineablePromise` types

packages/restate-sdk/src/context_impl.ts
At the moment a negative sleep duration causes the service to crash with this error
```
[restate][2025-05-13T08:31:17.172Z][greeter/greet][inv_18mP0bGrYLaj5Z610aSA2q60Kh2chnBoSG] DEBUG: Executing 'Timer with duration 18446744073709551.615s'
panicked at /home/slinkydeveloper/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/restate-sdk-shared-core-0.3.0/src/vm/mod.rs:678:22:
millis since Unix epoch should fit in u64: TryFromIntError(())
Stack:
Error
at imports.wbg.__wbg_new_8a6f238a6ece86ea (file:///Users/nik/Developer/sdk-typescript/packages/restate-sdk/src/endpoint/handlers/vm/sdk_shared_core_wasm_bindings.js:1383:17)
at wasm://wasm/00310276:wasm-function[1479]:0xa756e
at wasm://wasm/00310276:wasm-function[433]:0x5c4a3
at wasm://wasm/00310276:wasm-function[1030]:0x91d71
at …
```
=> Validate sleep duration is non-negative.

.gitignore, api-extractor.base.json, package-lock.json, package.json, packages/restate-sdk-clients/api-extractor.json, packages/restate-sdk-clients/package.json, packages/restate-sdk-clients/tsconfig.json, packages/restate-sdk-cloudflare-workers/api-extractor.json, packages/restate-sdk-cloudflare-workers/package.json, packages/restate-sdk-core/api-extractor.json, packages/restate-sdk-core/package.json, packages/restate-sdk-core/tsconfig.json, packages/restate-sdk-examples/tsconfig.json, packages/restate-sdk-testcontainers/api-extractor.json, packages/restate-sdk-testcontainers/package.json, packages/restate-sdk-testcontainers/tsconfig.json, packages/restate-sdk-zod/api-extractor.json, packages/restate-sdk-zod/package.json, packages/restate-sdk-zod/src/public_api.ts, packages/restate-sdk-zod/src/serde_api.ts, packages/restate-sdk-zod/tsconfig.json, packages/restate-sdk/api-extractor.json, packages/restate-sdk/package.json, packages/restate-sdk/tsconfig.json
```
Error: src/context.ts:272:1 - (ae-forgotten-export) The symbol "RestateContext" needs to be exported by the entry point public_api.d.ts
Error: src/context.ts:293:3 - (ae-forgotten-export) The symbol "ContextDate" needs to be exported by the entry point public_api.d.ts
Error: src/context.ts:338:3 - (ae-forgotten-export) The symbol "RunAction" needs to be exported by the entry point public_api.d.ts
Error: src/context.ts:349:3 - (ae-forgotten-export) The symbol "RunOptions" needs to be exported by the entry point public_api.d.ts
Error: src/context.ts:454:3 - (ae-forgotten-export) The symbol "ServiceDefinitionFrom" needs to be exported by the entry point public_api.d.ts
Error: src/context.ts:454:3 - (ae-forgotten-export) The symbol "Service" needs to be exported by the entry point …
```
=> Add `api-extractor` check to catch missing exports

packages/restate-e2e-services/src/app.ts, packages/restate-sdk/src/endpoint/handlers/generic.ts, packages/restate-sdk/src/endpoint/node_endpoint.ts
- Adds more logging to the end-to-end tests to count the number of connections and streams.  
-  Aims to be more defensive in handling streams instead of waiting for an error to occur and then catching it.
=> Improve error handling

packages/restate-sdk/src/endpoint/handlers/generic.ts
On AbortError we were not removing the logger, causing a leak.
=> Resolve leak on aborted invocation

README.md, packages/restate-sdk-cloudflare-workers/patches/fetch.js, packages/restate-sdk-examples/src/greeter.ts, packages/restate-sdk-examples/src/greeter_with_options.ts, packages/restate-sdk-examples/src/object.ts, packages/restate-sdk-examples/src/workflow.ts, packages/restate-sdk-examples/src/zod_greeter.ts, packages/restate-sdk-examples/test/hello.test.ts, packages/restate-sdk-examples/test/testcontainers.test.ts, packages/restate-sdk-testcontainers/src/public_api.ts, packages/restate-sdk-testcontainers/src/restate_test_environment.ts, packages/restate-sdk-zod/README.md, packages/restate-sdk/README.md, packages/restate-sdk/package.json, packages/restate-sdk/src/common_api.ts, packages/restate-sdk/src/context.ts, packages/restate-sdk/src/endpoint/types.ts, packages/restate-sdk/src/endpoint/withOptions.ts, packages/restate-sdk/src/fetch.ts, packages/restate-sdk/src/lambda.ts, packages/restate-sdk/src/node.ts, packages/restate-sdk/src/public_api.ts
This PR ~deprecates~ the old chained-style API based on `restate.endpoint().bind()...` and introduces a new, config-driven and runtime-explicit API based on `createEndpointHandler`.
- Introduced createEndpointHandler(config) as the new primary API for exposing services across all runtimes
- Added `serve(config)` as a convenience helper for fast development with Node.js
- Per-runtime entry points: 
- `@restatedev/restate-sdk/node`
- `@restatedev/restate-sdk/lambda`
- `@restatedev/restate-sdk/fetch`
- `@restatedev/restate-sdk-cloudflare-workers/fetch`
- The root package `@restatedev/restate-sdk` now defaults to Node-specific exports, for compatibility 
- The builder-style API in `RestateTestEnvironment.start` (from `@restatedev/restate-sdk-testcontainers`) has also been deprecated in favour …
=> Replace chained `endpoint` API with unified `createEndpointHandler`

packages/restate-sdk-cloudflare-workers/patches/fetch.js, packages/restate-sdk-testcontainers/src/restate_test_environment.ts, packages/restate-sdk/src/fetch.ts, packages/restate-sdk/src/lambda.ts, packages/restate-sdk/src/node.ts
We should not merge/publish this, until we updated docs and examples.
=> Deprecate `endpoint()` API
