restatedev/sdk-typescript

proto/protocol.proto
src/journal.ts
src/state_machine.ts
src/types/protocol.ts
src/types/types.ts
test/protoutils.ts
test/side_effect.test.ts
test/testdriver.ts

See https://github.com/restatedev/service-protocol/issues/53

Use the new REQUIRES_ACK flag and the EntryAckMessage

---

src/utils/utils.ts

Fix missing undefined check

---

src/restate_context.ts
src/restate_context_impl.ts
src/types/errors.ts
test/promise_combinators.test.ts

Introduce `CombineablePromise#orTimeout`

---

src/embedded/handler.ts
src/restate_context.ts
src/restate_context_impl.ts
src/server/base_restate_server.ts
src/state_machine.ts
src/types/router.ts
src/utils/promises.ts
src/utils/rand.ts

`Client` returns `CombineablePromise`

---

examples/example.ts
examples/grpc_example.ts
src/context.ts
src/context_impl.ts
src/embedded/api.ts
src/embedded/handler.ts
src/embedded/invocation.ts
src/public_api.ts
src/restate_context.ts
src/restate_context_impl.ts
src/server/base_restate_server.ts
src/server/restate_lambda_handler.ts
src/server/restate_server.ts
src/state_machine.ts
src/types/grpc.ts
src/types/router.ts
src/utils/rand.ts
src/workflows/workflow.ts
src/workflows/workflow_state_service.ts
src/workflows/workflow_wrapper_service.ts
test/eager_state.test.ts
test/get_and_set_state.test.ts
test/get_state.test.ts
test/lambda.test.ts
test/promise_combinators.test.ts
test/send_request.test.ts
test/side_effect.test.ts
test/sleep.test.ts
test/state_keys.test.ts
test/testdriver.ts

Context interface rework

---

examples/workflow_example.ts
src/clients/workflow_client.ts
src/context.ts
src/context_impl.ts
src/workflows/workflow.ts
src/workflows/workflow_state_service.ts
src/workflows/workflow_wrapper_service.ts
test/awakeable.test.ts
test/complete_awakeable.test.ts

Some feedback about workflow api

---

proto/protocol.proto
src/connection/lambda_connection.ts
src/endpoint/lambda_handler.ts
src/invocation.ts
src/io/decoder.ts
src/journal.ts
src/state_machine.ts
src/types/protocol.ts
src/types/types.ts
src/utils/utils.ts
test/protoutils.ts
test/state_machine.test.ts

Adapt to https://github.com/restatedev/service-protocol/commit/4378d559db7a53a477dd091b636a64712b2b630e

Changes in input/output messages

---

README.md
packages/restate-sdk-clients/src/api.ts
packages/restate-sdk/src/context.ts
packages/restate-sdk/src/endpoint.ts
packages/restate-sdk/src/public_api.ts
packages/restate-sdk/src/types/rpc.ts
packages/restate-sdk/src/workflows/workflow.ts
packages/restate-sdk/src/workflows/workflow_wrapper_service.ts

Fix #278 
This is not complete, and will need another pass, but it's a starting point.

Fix TSDocs and README

---

packages/restate-sdk-clients/README.md
packages/restate-sdk/README.md

Add README for each package

---

.github/workflows/publish.yml
.github/workflows/test.yml

Update workflow dependencies

---

packages/restate-sdk-core/src/core.ts

Fix ObjectSharedHandler definition

---

.eslintrc.json
package-lock.json
package.json
packages/restate-sdk/package.json
packages/restate-sdk/src/endpoint/cloudflare_endpoint.ts
packages/restate-sdk/src/endpoint/endpoint_builder.ts
packages/restate-sdk/src/endpoint/lambda_endpoint.ts
packages/restate-sdk/src/endpoint/node_endpoint.ts
packages/restate-sdk/test/lambda.test.ts

Enforces more well specified imports

Add import linter

---

.eslintrc.json
package-lock.json
package.json
packages/restate-sdk-clients/src/public_api.ts
packages/restate-sdk-examples/package.json
packages/restate-sdk/src/common_api.ts

Also fix some exports of type-only things which apparently tsx complains about.

Use tsx in examples repo

---

packages/restate-sdk/src/logger.ts
packages/restate-sdk/src/state_machine.ts

Ensure replayed logs aren't emitted

---

packages/restate-sdk/src/context_impl.ts

This simplifies a bit the problem with CombineablePromise, where now we first transform the result deserializing it, and then we wrap it in a combineable promise. It also makes consistent that the ser/de concern is within the invoke/invokeOneWay, and not on the caller.

ctx.invoke/invokeOneWay now accepts a serialization and deserialization function.

---

packages/restate-sdk/src/endpoint.ts

This is a leftover from the old workflow API

Deprecate ServiceBundle

---

packages/restate-e2e-services/exclusions.yaml
packages/restate-e2e-services/src/failing.ts
packages/restate-sdk/src/context.ts
packages/restate-sdk/src/context_impl.ts

Add run retry feature

---

packages/restate-sdk-clients/src/api.ts
packages/restate-sdk-clients/src/ingress.ts
packages/restate-sdk-examples/src/ingress_client.ts

Add options in ingress client to accept `timeout` or `signal`

---

packages/restate-sdk/src/endpoint/handlers/generic.ts
packages/restate-sdk/src/logger.ts

Add key to LoggerContext

---

packages/restate-sdk/src/endpoint/handlers/generic.ts

Bring back logging for start/end invocation

---

packages/restate-e2e-services/src/side_effect.ts
packages/restate-sdk-core/src/core.ts
packages/restate-sdk/src/types/rpc.ts
packages/restate-sdk/test/service_bind.test.ignore.ts

Improve type mismatching for handlers

---

packages/restate-sdk/src/types/rpc.ts
packages/restate-sdk/tsconfig.json
tsconfig.base.json

Fix `this` type

---

.gitignore
packages/restate-sdk/src/context_impl.ts

Handle case when delay is either 0 or undefined.
